### ISSUE TITLE
"Internal Failure" checking pull request (ERROR RUNNING CAPTURE: Bi_util.Error("Unterminated vint or vint exceeding range of OCaml ints"))

### ISSUE THREAD

**Issue by rokopt** [Muse-Dev/MuseDev#4]
Having signed up for early access to Muse, I tried it out for the first time yesterday on my fork of [stellar-core](https://github.com/stellar/stellar-core):

https://github.com/rokopt/stellar-core

At first, there were a couple of dependencies that Muse didn't know how to find, for which Dr. Magill generously volunteered fixes:

https://github.com/rokopt/stellar-core/pull/1

Dr. Magill's own Muse test run using those changes did succeed:

https://console.muse.dev/result/smagill/stellar-core/01EE3HV9F4ZY3CVEWDKQT726PC?tab=results

However, when I took the changes, and then created a test PR (which just added a NULL pointer dereference at some random spot in the code), Musebot reported an "Internal Failure":

https://github.com/rokopt/stellar-core/pull/2

https://console.muse.dev/result/rokopt/stellar-core/01EE4PX0R6H2VEK8CXJ43GC298?tab=logs

I of course know nothing about interpreting Muse's logs yet, but at a first glance, here are a couple of things that look possibly untoward:

```
Capture:
-----
Call Stack: 
------Execution Failed:
Capturing in make/cc mode...
Stack dump:
0.	Program arguments: /opt/infer-linux64/lib/infer/facebook-clang-plugins/clang/install/bin/clang-9 @/tmp/clang_command_.tmp.02a3e9.txt 
1.	<eof> parser at end of file
 #0 0x0000561be3660f8a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/infer-linux64/lib/infer/facebook-clang-plugins/clang/install/bin/clang-9+0x1ec8f8a)
 #1 0x0000561be365e7c5 llvm::sys::RunSignalHandlers() (/opt/infer-linux64/lib/infer/facebook-clang-plugins/clang/install/bin/clang-9+0x1ec67c5)
 #2 0x0000561be365e8dc (/opt/infer-linux64/lib/infer/facebook-clang-plugins/clang/install/bin/clang-9+0x1ec68dc)
 #3 0x00007fab30aa93c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #4 0x00007fab306b6650 (/lib/x86_64-linux-gnu/libc.so.6+0x18e650)
 #5 0x00007fab302fde9e llvm::APInt::APInt(llvm::APInt const&) /builds/musedev/infer/facebook-clang-plugins/clang/install/include/llvm/ADT/APInt.h:325:0
 #6 0x00007fab302fde9e llvm::APSInt::APSInt(llvm::APSInt const&) /builds/musedev/infer/facebook-clang-plugins/clang/install/include/llvm/ADT/APSInt.h:21:0
 #7 0x00007fab302fde9e ASTLib::ASTExporter<ATDWriter::BiniouWriter<llvm::raw_ostream> >::evaluateAndEmitInteger(clang::Expr const*) /builds/musedev/infer/facebook-clang-plugins/libtooling/ASTExporter.h:3629:0
 #8 0x00007fab302fde9e ASTLib::ASTExporter<ATDWriter::BiniouWriter<llvm::raw_ostream> >::VisitOffsetOfExpr(clang::OffsetOfExpr const*) /builds/musedev/infer/facebook-clang-plugins/libtooling/ASTExporter.h:3641:0
 #9 0x00007fab302fa218 clang::StmtVisitorBase<llvm::make_const_ptr, ASTLib::ASTExporter<ATDWriter::BiniouWriter<llvm::raw_ostream> >, void>::Visit(clang::Stmt const*) /builds/musedev/infer/facebook-clang-plugins/clang/install/include/clang/AST/StmtNodes.inc:1167:0
#10 0x00007fab302fac03 std::vector<ATDWriter::BiniouEmitter<llvm::raw_ostream>::ATDContainer, std::allocator<ATDWriter::BiniouEmitter<llvm::raw_ostream>::ATDContainer> >::pop_back() /usr/include/c++/6/bits/stl_vector.h:952:0
#11 0x00007fab302fac03 ATDWriter::BiniouEmitter<llvm::raw_ostream>::leaveContainer() /builds/musedev/infer/facebook-clang-plugins/libtooling/atdlib/ATDWriter.h:542:0
#12 0x00007fab302fac03 ATDWriter::BiniouEmitter<llvm::raw_ostream>::leaveTuple() /builds/musedev/infer/facebook-clang-plugins/libtooling/atdlib/ATDWriter.h:664:0
#13 0x00007fab302fac03 ATDWriter::GenWriter<ATDWriter::BiniouEmitter<llvm::raw_ostream> >::leaveTuple() /builds/musedev/infer/facebook-clang-plugins/libtooling/atdlib/ATDWriter.h:206:0
#14 0x00007fab302fac03 ATDWriter::GenWriter<ATDWriter::BiniouEmitter<llvm::raw_ostream> >::TupleScope::~TupleScope() /builds/musedev/infer/facebook-clang-plugins/libtooling/atdlib/ATDWriter.h:264:0
```
[ ... ]
```
#95 0x00007fab3054f0b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#96 0x0000561be240704a _start (/opt/infer-linux64/lib/infer/facebook-clang-plugins/clang/install/bin/clang-9+0xc6f04a)
Segmentation fault (core dumped)
ERROR RUNNING CAPTURE: Bi_util.Error("Unterminated vint or vint exceeding range of OCaml ints")
Raised at file "src/bi_util.ml", line 3, characters 14-29
Called from file "src/bi_vint.ml", line 92, characters 5-76
Called from file "src/bi_vint.ml", line 99, characters 21-36
```
[ ... ]
```
Called from file "infer.ml", line 25, characters 22-94
src/work/test/WorkTests.cpp:983:5-1003:5: ERROR translating statement 'CompoundStmt'
Aborting translation of method '____C_A_T_C_H____T_E_S_T____40' in file 'src/work/test/WorkTests.cpp': "Assert_failure clang/cAst_utils.ml:190:53"
Aborting translation of method '____C_A_T_C_H____T_E_S_T____40' in file 'src/work/test/WorkTests.cpp'
Frontend error: "Assert_failure clang/cAst_utils.ml:190:53"
Backtrace:
Raised by primitive operation at file "printexc.ml" (inlined), line 253, characters 0-75
Called from file "src/backtrace.ml" (inlined), line 11, characters 2-48
```

I'm not sure what the salient difference might have been between my test PR's run and Dr. Magill's; I think the code ought to have been the same aside from my trivial injected bug -- although I did take Dr. Magill's changes into a branch other than my repo's main branch, and made the PR from another branch to that one.

**Comment by TomMD** [comment]
@rokopt Thanks.  I know you've been talking with Stephen but I also wanted to mention that we are working on this issue. I'll spare you the long winded part and just say thank you for calling it out and being patient as we decide on how best to address the problems.  The hope was for a fix today but it appears to be a longer road, but we will keep you posted.

**Comment by rokopt** [comment]
> @rokopt Thanks. I know you've been talking with Stephen but I also wanted to mention that we are working on this issue. I'll spare you the long winded part and just say thank you for calling it out and being patient as we decide on how best to address the problems. The hope was for a fix today but it appears to be a longer road, but we will keep you posted.

No worries (at least on my behalf)!  Thanks for keeping in touch.

**Comment by TomMD** [comment]
Rather late notice: this is was addressed.  There were some scaling problems in our backend which killed long running jobs unnecessarily.  Thank you for the issue and do re-open if you experience anything similar.

**Comment by rokopt** [comment]
Thank you!  I just re-ran on the same branch, and the internal error didn't happen; I got results.
